---
apiVersion: v1
kind: Service
metadata:
  name: uss-api-svc
spec:
  selector:
    app: uss-api #Choosing pods to run on
  ports:
  - port: 80 #Port exposed on an API
    targetPort: 5000 #Port exposed by the application inside container
  type: NodePort #ClusterIP, NodePort, LoadBalancer, ExternalIP(Ingress)